# Site settings
title: Comparative modENCODE/ENCODE
email: encode-help@lists.stanford.edu
description: A website for a species comparison using modENCODE and ENCODE data.
baseurl: "/comparative-website"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
sass:
  sass_dir: _sass