# Site settings
title: Comparative modENCODE/ENCODE
email: peter_park@hms.harvard.edu
description: A website for a species comparison using modENCODE and ENCODE data.
baseurl: "/comparative-website"
url: "http://www.encodeproject.org/comparative"
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
sass:
  sass_dir: _sass