# Site settings
title: Comparative modENCODE/ENCODE
email: contact@c
description: "TODO: Short description of the project."
#baseurl: "http://parklab.github.io/comparative-website"
url: "http://encodeproject.org/comparative"
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
sass:
  sass_dir: _sass